Repository NoGiveUpWeCarry/front, pull requests merged in 2025-03, with the labels that each got.

#150 Feature/148 hub designfix
  src/components/atoms/Button.tsx
  src/components/molecules/HubDetailFooter.tsx
  src/components/molecules/hub/HubContentsThumbnail.tsx
  src/components/molecules/hub/HubDetailUser.tsx
  src/components/molecules/hub/HubInfo.tsx
  src/components/molecules/hub/HubIntroduce.tsx
  src/components/molecules/hub/HubItem.tsx
  src/components/molecules/hub/HubTopRoleSelect.tsx
  src/components/molecules/hub/HubUnitSelect.tsx
  src/components/organisms/hub/HubBody.tsx
  src/components/organisms/hub/HubContentTop.tsx
  src/components/organisms/hub/HubDetail.tsx
  src/components/organisms/sides/HubApplySideBar.tsx
  src/components/organisms/sides/HubApplyUserSideBar.tsx
Labels: 🎨 Html&css, 🔨 Refactor

#164 Feature/163 hub lazy
  src/components/organisms/Hub.tsx
  src/components/organisms/hub/HubContents.tsx
  src/constants/OptimizeImage.ts
  src/hooks/queries/hub.query.ts
  src/layouts/HubLayout.tsx
Labels: 🔨 Refactor

#166 [Bugfix] 피드 및 피드 상세 버그 수정
  index.html
  src/apis/feed.ts
  src/assets/fonts/Pretendard-Black.subset.woff2
  src/assets/fonts/Pretendard-Bold.subset.woff2
  src/assets/fonts/Pretendard-ExtraBold.subset.woff2
  src/assets/fonts/Pretendard-ExtraLight.subset.woff2
  src/assets/fonts/Pretendard-Light.subset.woff2
  src/assets/fonts/Pretendard-Medium.subset.woff2
  src/assets/fonts/Pretendard-Regular.subset.woff2
  src/assets/fonts/Pretendard-SemiBold.subset.woff2
  src/assets/fonts/Pretendard-Thin.subset.woff2
  src/components/molecules/ChatInput.tsx
  src/components/molecules/FeedDetailFooter.tsx
  src/components/molecules/FeedDetailUserInfo.tsx
  src/components/molecules/PadContact.tsx
  src/components/molecules/Popup.tsx
  src/components/molecules/feed/ContentsBody.tsx
  src/components/molecules/feed/FeedContentsThumbnail.tsx
  src/components/molecules/search/SearchResults.tsx
  src/components/organisms/feed/FeedDetailChat.tsx
  src/components/organisms/feed/FeedItem.tsx
  src/components/pages/FeedDetailPage.tsx
  src/components/templates/MyPage/MyPageTemplate.tsx
  src/hooks/queries/feed.query.ts
  src/hooks/queries/hub.query.ts
  src/hooks/useOutsideClick.ts
  src/index.css
  src/layouts/MainLayout.tsx
Labels: 🐞 BugFix

#167 [Bugfix] 162 layout
  src/components/molecules/Menu.tsx
  src/components/molecules/SideMenuLogo.tsx
  src/components/organisms/sides/NotificationList.tsx
  src/components/organisms/sides/SideMenu.tsx
  src/components/organisms/sides/SideMenuNavigation.tsx
  src/components/organisms/sides/SideMenuNotification.tsx
  src/components/organisms/sides/SideMenuProfile.tsx
  src/components/organisms/sse/NotificationProvider.tsx
  src/hooks/queries/feed.query.ts
  src/hooks/queries/hub.query.ts
  src/store/chatStore.ts
  src/utils/optimizeImage.ts
Labels: 🐞 BugFix

#176 [Bugfix] 검색 기능 관련 오류 수정
  src/components/molecules/search/SearchResults.tsx
  src/components/organisms/ConnectionHubDetail.tsx
  src/components/organisms/modals/SearchModal.tsx
  src/components/pages/FeedDetailPage.tsx
  src/components/pages/LoginPage.tsx
  src/components/pages/PadLoginPage.tsx
  src/components/templates/MyPage/FeedTemplate.tsx
Labels: 🐞 BugFix
