Repository NoGiveUpWeCarry/front, pull requests merged in 2025-02, with the labels that each got.

#119 채팅페이지 - 메시지 안 읽은 유저 수 표시
  src/components/organisms/chat/ChatMessages.tsx
  src/components/organisms/chat/Message.tsx
  src/components/templates/ChatTemplate.tsx
  src/hooks/chat/useMessages.ts
  src/store/chatStore.ts
  src/types/message.type.ts
Labels: ✨ Feature

#113 Feature/107 hub refactor
  src/apis/hub.api.ts
  src/components/atoms/contents/ContentsHubToggle.tsx
  src/components/molecules/HubDetailFooter.tsx
  src/components/molecules/contents/HubContentTop.tsx
  src/components/molecules/contents/HubDetail.tsx
  src/components/molecules/contents/HubIntroduce.tsx
  src/components/organisms/ConnectionHubDetail.tsx
  src/components/organisms/modals/PostHubContentFirst.tsx
  src/components/organisms/modals/PostHubContentSecond.tsx
  src/components/organisms/sides/SideBarApplicantList.tsx
  src/components/templates/MyPage/ConnectionHubTemplate.tsx
  src/components/templates/MyPage/FeedTemplate.tsx
  src/components/templates/MyPage/MyPageTemplate.tsx
  src/store/chatStore.ts
  src/store/hubSeartchStore.ts
Labels: 📬 API, ✨ Feature

#127 [Feature] 아바타 팝업 구현
  src/apis/feed.ts
  src/apis/notification.api.ts
  src/components/molecules/AvatarPopup.tsx
  src/components/molecules/FeedDetailUserInfo.tsx
  src/components/molecules/HubDetailFooter.tsx
  src/components/molecules/Popup.tsx
  src/components/molecules/chat/ChannelExitButton.tsx
  src/components/molecules/chat/ChatInput.tsx
  src/components/molecules/contents/ContentsHubUser.tsx
  src/components/molecules/contents/ContentsUser.tsx
  src/components/molecules/contents/HubDetail.tsx
  src/components/molecules/contents/HubUnitSelect.tsx
  src/components/molecules/side/HubSideBarContents.tsx
  src/components/molecules/side/MainSideBarContents.tsx
  src/components/organisms/ConnectionHubDetail.tsx
  src/components/organisms/modals/FollowersModal.tsx
  src/components/organisms/modals/PostFeedModal.tsx
  src/components/organisms/search/ProjectView.tsx
  src/components/organisms/sides/Notifications.tsx
  src/components/organisms/sides/SideBarApplicantList.tsx
  src/components/organisms/sides/SideMenu.tsx
  src/components/pages/FeedDetailPage.tsx
  src/components/pages/TestPage.tsx
  src/hooks/queries/feed.query.ts
  src/hooks/queries/hub.query.ts
  src/hooks/queries/notification.query.ts
  src/hooks/usePostModal.ts
  src/mocks/handlers/feedHandler.mock.ts
  src/store/chatStore.ts
  src/types/search.type.ts
Labels: ✨ Feature

#131 [Fix] 이미지 import 수정 및 추천 피드/프로젝트 url 연결
  src/components/atoms/Logo.tsx
  src/components/molecules/AvatarPopup.tsx
  src/components/molecules/LinkInput.tsx
  src/components/molecules/MyPageHeader.tsx
  src/components/molecules/MyPageProjectCard.tsx
  src/components/molecules/Popup.tsx
  src/components/molecules/side/HubSideBarContents.tsx
  src/components/molecules/side/MainSideBarContents.tsx
  src/components/organisms/modals/AddProjectModal.tsx
  src/components/organisms/modals/FollowersModal.tsx
  src/components/organisms/sides/SideMenu.tsx
  src/constants/mypageLinks.ts
Labels: 🐞 BugFix
