Repository NoGiveUpWeCarry/front, pull requests merged in 2025-01, with the labels that each got.

#34 [Feature] 탭 컴포넌트 구현
  package-lock.json
  package.json
  src/components/atoms/TabsButton.tsx
  src/components/atoms/VerticalDivider.tsx
  src/components/molecules/.gitkeep
  src/components/molecules/TabItem.tsx
  src/components/organisms/.gitkeep
  src/components/organisms/Tabs.tsx
  src/components/pages/.gitkeep
  src/components/pages/MyPage.tsx
  src/components/templates/.gitkeep
  src/components/templates/MyPageTemplate.tsx
  src/store/.gitkeep
  src/store/tabStore.tsx
  tailwind.config.ts
Labels: ✨ Feature

#40 [Feature] 버튼 컴포넌트
  src/components/atoms/Button.tsx
  src/components/atoms/TabsButton.tsx
Labels: ✨ Feature

#38 [Feature] 모달 컴포넌트
  package.json
  pnpm-lock.yaml
  src/components/organisms/modals/Modal.tsx
  src/components/pages/ChatPage.tsx
  src/components/pages/MainPage.tsx
  tailwind.config.ts
Labels: ✨ Feature

#43 [Fix] Font Weight 수정
  src/components/atoms/TabsButton.tsx
  tailwind.config.ts
Labels: 🐞 BugFix

#45 Feature/24 main connection page 아이콘 컴포넌트
  src/assets/images/example.svg
  src/assets/logo/PAD.svg
  src/components/atoms/Icon.tsx
  src/components/atoms/Logo.tsx
  src/components/molecules/Menu.tsx
  src/components/organisms/SideBar.tsx
  src/components/pages/HomePage.tsx
  src/components/pages/MainPage.tsx
  src/layouts/Layouts.tsx
  src/routes/router.tsx
Labels: ✨ Feature, 🎨 Html&css

#46 [Feature] 마이페이지 소개 탭, 지원 탭 구현
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/assets/.gitkeep
  src/assets/icons/android.svg
  src/assets/icons/apple.svg
  src/assets/icons/figma.svg
  src/assets/icons/github.svg
  src/assets/icons/linkedin.svg
  src/assets/icons/notion.svg
  src/components/atoms/Button.tsx
  src/components/atoms/DateText.tsx
  src/components/atoms/FollowButton.tsx
  src/components/atoms/HorizontalDivider.tsx
  src/components/atoms/Input.tsx
  src/components/atoms/Label.tsx
  src/components/molecules/ContributionBox.tsx
  src/components/molecules/InputWithLabel.tsx
  src/components/molecules/MyPageHeader.tsx
  src/components/molecules/MyPageProjectCard.tsx
  src/components/molecules/UrlInput.tsx
  src/components/organisms/ApplyFormSection/ApplyFormSection.tsx
  src/components/organisms/ApplyFormSection/ApplyFormTextArea.tsx
  src/components/organisms/ApplyFormSection/Input.tsx
  src/components/organisms/WorkList.tsx
  src/components/organisms/modals/AddMusicModal.tsx
  src/components/organisms/modals/AddProjectModal.tsx
  src/components/organisms/modals/FollowersModal.tsx
  src/components/organisms/modals/Modal.tsx
  src/components/pages/ChatPage.tsx
  src/components/pages/MyPage.tsx
  src/components/templates/MyPage/ApplyTemplate.tsx
  src/components/templates/MyPage/ConnectionHubTemplate.tsx
  src/components/templates/MyPage/FeedTemplate.tsx
  src/components/templates/MyPage/IntroductionTemplate.tsx
  src/components/templates/MyPage/MyPageTemplate.tsx
  src/components/templates/MyPageTemplate.tsx
  src/routes/router.tsx
  src/store/addProjectFormStore.tsx
  src/store/applyFormStore.tsx
  src/store/followsStore.tsx
  tailwind.config.ts
Labels: ✨ Feature

#48 Feature/22 login/signup
  .gitignore
  package.json
  pnpm-lock.yaml
  src/apis/.gitkeep
  src/apis/@core.ts
  src/apis/api-path.ts
  src/apis/auth.ts
  src/assets/icons/Github.svg
  src/assets/icons/Google.svg
  src/assets/logos/ArtistLogo.svg
  src/assets/logos/DefaultLogo.svg
  src/assets/logos/DesignerLogo.svg
  src/assets/logos/ProgrammerLogo.svg
  src/components/.gitkeep
  src/components/atoms/LoginButton.tsx
  src/components/molecules/RoleSelectLogo.tsx
  src/components/pages/CallbackPage.tsx
  src/components/pages/LoginPage.tsx
  src/components/pages/RolePage.tsx
  src/components/templates/LoginTemplate.tsx
  src/hooks/queries/.gitkeep
  src/hooks/queries/auth.query.ts
  src/routes/router.tsx
  src/store/useAuth.ts
  src/types/.gitkeep
  src/types/auth.type.ts
  src/types/role.type.ts
  src/types/user.type.ts
  src/utils/fetcher.ts
Labels: 📬 API, ✨ Feature, 🎨 Html&css, ⚙ Setting

#50 Feature/24 main connection page
  src/assets/Genericavatar.svg
  src/assets/images/contentimagetest.png
  src/components/atoms/Avatar.tsx
  src/components/atoms/Role.tsx
  src/components/atoms/SideBarTitle.tsx
  src/components/atoms/Tag.tsx
  src/components/atoms/contents/ConentsUserTitle.tsx
  src/components/atoms/contents/ContentsBody.tsx
  src/components/atoms/contents/ContentsThumbnail.tsx
  src/components/atoms/contents/ContentsTime.tsx
  src/components/atoms/contents/ContentsTitle.tsx
  src/components/molecules/ListItem.tsx
  src/components/molecules/Menu.tsx
  src/components/molecules/PadContact.tsx
  src/components/molecules/SideBarContents.tsx
  src/components/molecules/contents/ContentsFooter.tsx
  src/components/molecules/contents/ContentsItem.tsx
  src/components/molecules/contents/ContentsUser.tsx
  src/components/molecules/contents/FeedBody.tsx
  src/components/molecules/contents/FeedItem.tsx
  src/components/molecules/contents/HubBody.tsx
  src/components/molecules/contents/HubItem.tsx
  src/components/molecules/contents/HubTitle.tsx
  src/components/organisms/Feed.tsx
  src/components/organisms/Hub.tsx
  src/components/organisms/sides/SideBar.tsx
  src/components/organisms/sides/SideMenu.tsx
  src/components/pages/ConnectionHubPage.tsx
  src/components/pages/HomePage.tsx
  src/index.css
  src/layouts/MainLayout.tsx
  src/layouts/SubLayout.tsx
  src/mock/connectionHubSideBar.ts
  src/mock/feedItem.ts
  src/mock/hubItem.ts
  src/mock/mainSideBar.ts
  src/routes/router.tsx
  src/types/tags/contentsFeedTag.type.ts
  src/types/tags/hubTag.type.ts
  src/types/tags/index.tag.ts
  src/types/tags/projectTag.type.ts
  src/types/tags/roleTag.type.ts
Labels: ✨ Feature, 🎨 Html&css

#54 Feature/51 side menu bar
  components.json
  package.json
  pnpm-lock.yaml
  src/components/atoms/contents/ContentsSelect.tsx
  src/components/atoms/contents/ContentsToggle.tsx
  src/components/molecules/Menu.tsx
  src/components/molecules/contents/ContentsTop.tsx
  src/components/molecules/contents/FeedItem.tsx
  src/components/organisms/sides/SideMenu.tsx
  src/components/pages/ConnectionHubPage.tsx
  src/components/pages/HomePage.tsx
  src/components/ui/Select.tsx
  src/components/ui/toggle-group.tsx
  src/components/ui/toggle.tsx
  src/index.css
  src/layouts/Layouts.tsx
  src/lib/utils.ts
  src/mock/feedItem.ts
  src/mock/hubItem.ts
  src/types/feed.type.ts
  src/types/tags/index.tag.ts
  tailwind.config.ts
  tsconfig.json
Labels: ✨ Feature, 🎨 Html&css

#59 [Feature] 검색 페이지 및 검색 모달
  src/components/molecules/search/ShortFeed.tsx
  src/components/molecules/search/ShortProject.tsx
  src/components/organisms/Feed.tsx
  src/components/organisms/Hub.tsx
  src/components/organisms/modals/Modal.tsx
  src/components/organisms/modals/SearchModal.tsx
  src/components/organisms/sides/SideMenu.tsx
  src/components/pages/SearchPage.tsx
  src/layouts/MainLayout.tsx
  src/mock/hubItem.ts
  src/routes/router.tsx
Labels: ✨ Feature

#61 Feature/28 connection hub
  src/components/atoms/Icon.tsx
  src/components/atoms/Tag.tsx
  src/components/atoms/contents/Behind.tsx
  src/components/atoms/contents/ContentsSelect.tsx
  src/components/atoms/contents/HubDetailUser.tsx
  src/components/molecules/contents/HubDetail.tsx
  src/components/molecules/contents/HubDetailTitle.tsx
  src/components/molecules/contents/HubInfo.tsx
  src/components/molecules/contents/HubInfoTag.tsx
  src/components/molecules/contents/HubIntroduce.tsx
  src/components/molecules/contents/HubTitle.tsx
  src/components/organisms/sides/SideBar.tsx
  src/components/pages/ConnetcionHubDetailPage.tsx
  src/routes/router.tsx
  src/types/tags/hubSkillTag.type.ts
Labels: 🎨 Html&css

#79 Feature/74 hub write
  package.json
  pnpm-lock.yaml
  src/components/atoms/contents/ContentsSelect.tsx
  src/components/molecules/Modal/modal-input.tsx
  src/components/molecules/Modal/modal-root.tsx
  src/components/molecules/Modal/modal-sub-content.tsx
  src/components/molecules/SideBarContents.tsx
  src/components/molecules/contents/ContentsTop.tsx
  src/components/organisms/TiptapEditor.tsx
  src/components/organisms/modals/PostFeedModal.tsx
  src/components/organisms/modals/PostHubModal.tsx
  src/components/organisms/sides/SideMenu.tsx
  src/components/pages/ConnectionHubPage.tsx
  src/components/pages/ConnetcionHubDetailPage.tsx
  src/components/ui/Select.tsx
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
  src/components/ui/input.tsx
  src/components/ui/popover.tsx
Labels: ✨ Feature, 🎨 Html&css

#80 [Feature] 마이페이지 API 연결
  index.html
  package.json
  pnpm-lock.yaml
  src/apis/auth.ts
  src/apis/mypage.ts
  src/components/atoms/DateText.tsx
  src/components/atoms/Icon.tsx
  src/components/atoms/TabsButton.tsx
  src/components/atoms/contents/ContentsBody.tsx
  src/components/atoms/contents/ContentsThumbnail.tsx
  src/components/molecules/ContributionBox.tsx
  src/components/molecules/LinkInput.tsx
  src/components/molecules/MyPageHeader.tsx
  src/components/molecules/MyPageProjectCard.tsx
  src/components/molecules/TabItem.tsx
  src/components/molecules/contents/ContentsItem.tsx
  src/components/molecules/contents/FeedBody.tsx
  src/components/molecules/contents/FeedItem.tsx
  src/components/organisms/ApplyFormSection/ApplyFormTextArea.tsx
  src/components/organisms/ApplyFormSection/Input.tsx
  src/components/organisms/Tabs.tsx
  src/components/organisms/WorkList.tsx
  src/components/organisms/modals/AddMusicModal.tsx
  src/components/organisms/modals/AddProjectModal.tsx
  src/components/organisms/modals/FollowersModal.tsx
  src/components/organisms/modals/SearchModal.tsx
  src/components/organisms/sides/SideMenu.tsx
  src/components/templates/MyPage/ApplyTemplate.tsx
  src/components/templates/MyPage/ConnectionHubTemplate.tsx
  src/components/templates/MyPage/FeedTemplate.tsx
  src/components/templates/MyPage/IntroductionTemplate.tsx
  src/components/templates/MyPage/MyPageTemplate.tsx
  src/constants/userStatus.ts
  src/hooks/queries/auth.query.ts
  src/hooks/queries/mypage/apply.ts
  src/hooks/queries/mypage/connection-hub.ts
  src/hooks/queries/mypage/feed.ts
  src/hooks/queries/mypage/introduce.ts
  src/hooks/useTabs.ts
  src/layouts/MainLayout.tsx
  src/routes/router.tsx
  src/store/addProjectFormStore.ts
  src/store/applyFormStore.ts
  src/store/followsStore.ts
  src/store/myTabsStore.ts
  src/store/mypageStore.ts
  src/store/tabStore.ts
  src/types/mypage.type.ts
  src/utils/fetcher.ts
Labels: 🐞 BugFix, ✨ Feature

#90 [Fix] 빌드 에러 해결
  pnpm-lock.yaml
  src/apis/feed.ts
  src/components/atoms/contents/ContentsBody.tsx
  src/components/atoms/contents/ContentsSelect.tsx
  src/components/molecules/RoleSelectLogo.tsx
  src/components/molecules/contents/ContentsFooter.tsx
  src/components/molecules/contents/ContentsItem.tsx
  src/components/molecules/contents/FeedBody.tsx
  src/components/molecules/contents/FeedItem.tsx
  src/components/molecules/contents/HubDetail.tsx
  src/components/molecules/contents/HubItem.tsx
  src/components/molecules/contents/HubTitle.tsx
  src/components/molecules/search/ShortFeed.tsx
  src/components/molecules/search/ShortProject.tsx
  src/components/molecules/side/SideBarContents.tsx
  src/components/organisms/ConnectionHubDetail.tsx
  src/components/organisms/Feed.tsx
  src/components/organisms/Hub.tsx
  src/components/organisms/chat/Message.tsx
  src/components/organisms/modals/FeedDetailModal.tsx
  src/components/organisms/modals/PostHubModal.tsx
  src/components/organisms/modals/SearchModal.tsx
  src/components/organisms/modals/SelectDetailJobModal.tsx
  src/components/organisms/settings/InfoSection.tsx
  src/components/organisms/sides/SideBar.tsx
  src/components/pages/RolePage.tsx
  src/components/pages/SearchPage.tsx
  src/hooks/queries/feed.query.ts
  src/hooks/tiptap/useEnhancedImage.ts
  src/mocks/handlers/chat.handler.ts
  src/mocks/mock-data/connectionHubSideBar.ts
  src/mocks/mock-data/detailItem.ts
  src/mocks/mock-data/feed.mock.ts
  src/mocks/mock-data/feedDetailComments.mock.ts
  src/mocks/mock-data/feedItem.ts
  src/store/chatStore.ts
  src/utils/fetcher.ts
  src/utils/format.ts
Labels: 🐞 BugFix

#103 Feature/93 design fix
  pnpm-lock.yaml
  src/components/atoms/contents/ConentsUserTitle.tsx
  src/components/atoms/contents/FeedContentsSelect.tsx
  src/components/molecules/ChatInput.tsx
  src/components/molecules/FeedDetailUserInfo.tsx
  src/components/molecules/contents/FeedDetail.tsx
  src/components/molecules/contents/HubBody.tsx
  src/components/molecules/feedDetailTag.tsx
  src/components/organisms/FeedDetailChat.tsx
  src/components/organisms/sides/SideMenu.tsx
  src/components/pages/FeedDetailPage.tsx
  src/index.css
  src/layouts/MainLayout.tsx
  src/mocks/mock-data/hub.mock.ts
  src/mocks/mock-data/hubDetail.mock.ts
Labels: 🎨 Html&css

#104 [Feature] 검색 모달 및 페이지 API 연결
  src/apis/feed.api.ts
  src/apis/search.ts
  src/components/atoms/contents/ConentsUserTitle.tsx
  src/components/molecules/contents/ContentsUser.tsx
  src/components/molecules/contents/FeedBody.tsx
  src/components/molecules/contents/HubBody.tsx
  src/components/molecules/search/SearchResults.tsx
  src/components/molecules/search/ShortFeed.tsx
  src/components/molecules/search/ShortProject.tsx
  src/components/molecules/side/MainSideBarContents.tsx
  src/components/organisms/ConnectionHubDetail.tsx
  src/components/organisms/chat/Message.tsx
  src/components/organisms/modals/SearchModal.tsx
  src/components/organisms/search/FeedView.tsx
  src/components/organisms/search/ProjectView.tsx
  src/components/organisms/sides/SideMenu.tsx
  src/components/pages/FeedDetailPage.tsx
  src/components/pages/SearchPage.tsx
  src/hooks/queries/search.query.ts
  src/hooks/useHandlePopState.ts
  src/mocks/handlers/feedHandler.mock.ts
  src/mocks/mock-data/feed.mock.ts
  src/mocks/mock-data/feedDetailComments.mock.ts
  src/mocks/mock-data/hubDetail.mock.ts
  src/mocks/mock-data/user.mock.ts
  src/routes/router.tsx
  src/store/chatStore.ts
  src/store/modals/searchModalstore.ts
  src/store/searchTabsStore.ts
  src/types/search.type.ts
  src/utils/fetcher.ts
  src/utils/format.ts
Labels: ✨ Feature

#101 [Feature] 마이페이지 및 세팅페이지 API 연결
  src/apis/@core.ts
  src/apis/auth.ts
  src/apis/feed.api.ts
  src/apis/hub.api.ts
  src/apis/mypage.ts
  src/components/molecules/FeedDetailUserInfo.tsx
  src/components/molecules/LinkInput.tsx
  src/components/molecules/MyPageHeader.tsx
  src/components/molecules/UrlInput.tsx
  src/components/molecules/mypage/Job.tsx
  src/components/molecules/mypage/StatusDropdown.tsx
  src/components/organisms/ConnectionHubDetail.tsx
  src/components/organisms/Hub.tsx
  src/components/organisms/LinkBox.tsx
  src/components/organisms/WorkList.tsx
  src/components/organisms/modals/AddMusicModal.tsx
  src/components/organisms/modals/AddProjectModal.tsx
  src/components/organisms/settings/InfoSection.tsx
  src/components/organisms/settings/NotificationSection.tsx
  src/components/organisms/sides/SideMenu.tsx
  src/components/templates/MyPage/FeedTemplate.tsx
  src/components/templates/MyPage/IntroductionTemplate.tsx
  src/hooks/queries/auth.query.ts
  src/hooks/queries/feed.query.ts
  src/hooks/queries/mypage/introduce.ts
  src/hooks/queries/mypage/settings.ts
  src/mocks/handlers/chat.handler.ts
  src/mocks/handlers/feedHandler.mock.ts
  src/store/authStore.ts
  src/store/mypageStore.ts
  src/store/settingsStore.ts
Labels: ✨ Feature
